// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MyNotes.UI.Web.Controllers {
    public partial class AdminController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SaveGroup() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SaveGroup);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SaveUser() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SaveUser);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController Actions { get { return MVC.Admin; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Admin";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Groups = "Groups";
            public readonly string Users = "Users";
            public readonly string AddGroup = "AddGroup";
            public readonly string SaveGroup = "SaveGroup";
            public readonly string AddUser = "AddUser";
            public readonly string SaveUser = "SaveUser";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Index = "Index";
            public const string Groups = "Groups";
            public const string Users = "Users";
            public const string AddGroup = "AddGroup";
            public const string SaveGroup = "SaveGroup";
            public const string AddUser = "AddUser";
            public const string SaveUser = "SaveUser";
        }


        static readonly ActionParamsClass_SaveGroup s_params_SaveGroup = new ActionParamsClass_SaveGroup();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveGroup SaveGroupParams { get { return s_params_SaveGroup; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveGroup {
            public readonly string groupViewModel = "groupViewModel";
        }
        static readonly ActionParamsClass_SaveUser s_params_SaveUser = new ActionParamsClass_SaveUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveUser SaveUserParams { get { return s_params_SaveUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveUser {
            public readonly string userViewModel = "userViewModel";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _addGroup = "~/Views/Admin/_addGroup.cshtml";
            public readonly string _addUser = "~/Views/Admin/_addUser.cshtml";
            public readonly string _groups = "~/Views/Admin/_groups.cshtml";
            public readonly string _users = "~/Views/Admin/_users.cshtml";
            public readonly string Index = "~/Views/Admin/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AdminController: MyNotes.UI.Web.Controllers.AdminController {
        public T4MVC_AdminController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Groups() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Groups);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Users() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Users);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddGroup() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddGroup);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SaveGroup(MyNotes.UI.Web.ViewModels.Admin.GroupViewModel groupViewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SaveGroup);
            callInfo.RouteValueDictionary.Add("groupViewModel", groupViewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddUser() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddUser);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SaveUser(MyNotes.UI.Web.ViewModels.User.UserViewModel userViewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SaveUser);
            callInfo.RouteValueDictionary.Add("userViewModel", userViewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
